apiVersion: sro.openshift.io/v1beta1
kind: SpecialResource
metadata:
  name: simple-kmod-2
spec:
  #debug: true 
  namespace: simple-kmod-2
  chart:
    name: simple-kmod-2
    version: 0.0.1
    repository:
      name: example
      url: cm://simple-kmod-2/simple-kmod-2-chart 
  set:
    kind: Values
    apiVersion: sro.openshift.io/v1beta1
    kmodNames: ["simple-kmod", "simple-procfs-kmod"]
    buildArgs:
    - name: "KMODVER"
      value: "SRO"
  driverContainer:
    source:
      git:
        ref: "master"
        uri: "https://github.com/aravid-marvell/kvc-simple-kmod.git"
